### ISSUE TITLE
GitHub私有仓库免费

### ISSUE THREAD

**Issue by Aemple** [FreeCodeCamp-Chengdu/IT-Technology-weekly#54]
2019年1月7日，GitHub推送了最新博文《New year, new GitHub: Announcing unlimited free private repos and unified Enterprise offering》，主要有两个更新：
1、私有存储库免费
没有数量限制、每个仓库支持最多3个开发者协作。
2、统一了企业云和企业服务器
统一化的企业云（GitHub Businiess Cloud）和企业服务器（GitHub Enterprise），可以使用GitHub Connect进行无缝连接。
链接：https://blog.github.com/2019-01-07-new-year-new-github/

**Comment by FengShangWuQi** [comment]
该条资讯已经收录 45 期
https://github.com/FreeCodeCamp-Chengdu/IT-Technology-weekly/blob/master/docs/issue-45.md
